config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'

  # Вложенные в ресурсы события
  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]
  end

  resources :users
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # пользователь может создавать много событий
  has_many :events

  # пользователь может оставлять много комментариев
  has_many :comments
  has_many :subscriptions

  validates :name,
            presence: true,
            length: { maximum: 35 }

  before_validation :set_name, on: :create

  after_commit :link_subscriptions, on: :create

  mount_uploader :avatar, AvatarUploader

  private

  def link_subscriptions
    Subscription.where(user_id: nil, user_email: self.email)
      .update_all(user_id: self.id)
  end

  def set_name
    self.name = "Пользователь №#{rand(999)}" if self.name.blank?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  before_action :set_current_user, except: [:show]

  # GET /users/1
  def show
    @user = User.find(params[:id])

    @user_past_events = []
    @user_upcoming_events = []

    @user.events.all.each do |item|
      if item.datetime < Time.now
        @user_past_events << item
      else
        @user_upcoming_events << item
      end
    end
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: I18n.t('controllers.users.updated') }
      else
        format.html { render :edit }
      end
    end
  end

  private

  def set_current_user
    @user = current_user
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, html: { multipart: true } do |f| %>

  <%= render partial: 'partials/form_errors', locals: {model: @user} %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :avatar %>
    <p><%= image_tag(@user.avatar.thumb.url) if @user.avatar? %></p>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit 'Сохранить', class: 'btn btn-primary' %> или <%= link_to 'вернуться', :back %>
  </div>
<% end %>

app/views/users/_user.html.erb
<span class="user">
  <span class="user-avatar">
    <%= image_tag user_avatar_thumb(user), class: 'img-icon mt-2 ml-1' %>
  </span>
  <span class="user-name">
    <% if request.path == user_path(user) %>
    <em><%= user.name %></em>
    <% else %>
      <%= link_to user.name, user_path(user) %>
    <% end %>
  </span>
</span>

app/views/users/edit.html.erb
<h1>Редактирование профиля</h1>

<div class="row container">
  <div class="col-md-8 col-lg-6 col-xl-5 buffer-top border rounded p-3 shadow background-color">

    <%= render 'form' %>

    <p class="buffer-top">
      <%= link_to 'Сменить пароль', edit_user_registration_path %>
    </p>
  </div>
</div>

app/views/users/show.html.erb
<div class="text-center border rounded p-3 shadow">
  <h1><%= @user.name %></h1>

  <%= image_tag user_avatar(@user), class: 'rounded width-img' %>

  <% if @user == current_user %>
    <p class="buffer-top">
      <%= link_to "Редактировать профиль", edit_user_path(@user), class: 'btn btn-outline-secondary' %>
    </p>
    <div class="buffer-both">
      <%= link_to 'Предложить новое событие', new_event_path, class: 'btn btn-success' %>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-12">

      <% if @user.events.any? %>
        <h3>Организовал:</h3>

        <% if @user_upcoming_events.size == 0  %>
          <p class="buffer-top mb-4">У пользователя пока нет предстоящих мероприятий</p>
        <% end %>

        <div class="row">
          <%= render partial: 'events/event', collection: @user.events.all.order(datetime: :asc) %>
        </div>

        <% if @user_past_events.size > 0 %>
          <h3>Прошедшие мероприятия:</h3>
          <div class="row">
            <%= render partial: 'events/past_events' %>
          </div>
        <% end %>
      <% else %>
        <p class="buffer-top">Пользователь пока не организовал ни одного события</p>
      <% end %>
    </div>
  </div>
</div>